version: "1.0"
info:
  model: int-scaffold
services:
- serviceName: pub.string:concat
  packages:
  - name: WmPublic
    version: 11.0.0.0.473
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.0.0.0.473
- serviceName: edge.se_tlundstr6.integrations:Hello
  packages:
  - name: EdgeSE_tlundstr6
    version: "1.0"
- serviceName: pub.client:http
  packages:
  - name: WmPublic
    version: 11.0.0.0.473
- serviceName: t2utilities.simulator:getProductSales
  packages:
  - name: T2Utilities
    version: "1.0"
- serviceName: pub.client:restClient
  packages:
  - name: WmPublic
    version: 11.0.0.0.473
- serviceName: edge.se_tlundstr6.integrations:getProducts
  packages:
  - name: EdgeSE_tlundstr6
    version: "1.0"
  - name: T2Utilities
    version: "1.0"
- serviceName: pub.json:jsonStreamToDocument
  packages:
  - name: WmPublic
    version: 11.0.0.0.473
- serviceName: pub.flow:clearPipeline
  packages:
  - name: WmPublic
    version: 11.0.0.0.473
- serviceName: t2utilities.utils:sleep
  packages:
  - name: T2Utilities
    version: "1.0"
- serviceName: edge.se_tlundstr6.integrations:startStreamsetJob
  packages:
  - name: EdgeSE_tlundstr6
    version: "1.0"
  - name: T2Utilities
    version: "1.0"
- serviceName: t2utilities.streamsets:startStreamsetsJob
  packages:
  - name: T2Utilities
    version: "1.0"
- serviceName: pub.json:jsonStringToDocument
  packages:
  - name: WmPublic
    version: 11.0.0.0.473
packages:
- name: EdgeSE_tlundstr6
  gitServerName: tlundstr_git
  gitUrl: https://github.com/tlundstr/EdgeSE_tlundstr6
  gitUsername: tlundstr
  gitToken: edge.scaffolding.EdgeSE_tlundstr6.tlundstr_git.gitToken
  gitBranch: main
- name: T2Utilities
  gitServerName: tlundstr_git
  gitUrl: https://github.com/tlundstr
  gitUsername: tlundstr
  gitToken: edge.scaffolding.T2Utilities.tlundstr_git.gitToken
  gitBranch: master
